version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 961126
      POSTGRES_DB: base_api
    volumes:
      - ./database/postgres:/var/lib/postgresql/data

  redis:
    image: redis
    networks:
      - base-api
    ports:
      - 6379:6379

networks:
  base-api:
